from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/telephone-call.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.ngrok_url = QtWidgets.QLineEdit(self.centralwidget)
        self.ngrok_url.setObjectName("ngrok_url")
        self.gridLayout_5.addWidget(self.ngrok_url, 0, 0, 1, 2)
        self.server_frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.server_frame.sizePolicy().hasHeightForWidth())
        self.server_frame.setSizePolicy(sizePolicy)
        self.server_frame.setStyleSheet("QFrame{\n"
"    border:1px solid #ABABAB;\n"
"}")
        self.server_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.server_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.server_frame.setObjectName("server_frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.server_frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.server_video = QtWidgets.QLabel(self.server_frame)
        self.server_video.setStyleSheet("QLabel{border:none;}")
        self.server_video.setText("")
        self.server_video.setObjectName("server_video")
        self.gridLayout_2.addWidget(self.server_video, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.server_frame, 1, 0, 1, 1)
        self.client_1_frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.client_1_frame.sizePolicy().hasHeightForWidth())
        self.client_1_frame.setSizePolicy(sizePolicy)
        self.client_1_frame.setStyleSheet("QFrame{\n"
"    border:1px solid #ABABAB;\n"
"}")
        self.client_1_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.client_1_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.client_1_frame.setObjectName("client_1_frame")
        self.gridLayout = QtWidgets.QGridLayout(self.client_1_frame)
        self.gridLayout.setObjectName("gridLayout")
        self.client_1_accept = QtWidgets.QPushButton(self.client_1_frame)
        self.client_1_accept.setObjectName("client_1_accept")
        self.gridLayout.addWidget(self.client_1_accept, 1, 0, 1, 1)
        self.client_1_stop = QtWidgets.QPushButton(self.client_1_frame)
        self.client_1_stop.setObjectName("client_1_stop")
        self.gridLayout.addWidget(self.client_1_stop, 0, 2, 1, 1)
        self.client_1_label = QtWidgets.QLabel(self.client_1_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.client_1_label.sizePolicy().hasHeightForWidth())
        self.client_1_label.setSizePolicy(sizePolicy)
        self.client_1_label.setStyleSheet("QLabel{\n"
"    border:none;\n"
"}")
        self.client_1_label.setObjectName("client_1_label")
        self.gridLayout.addWidget(self.client_1_label, 0, 0, 1, 2)
        self.client_1_video = QtWidgets.QLabel(self.client_1_frame)
        self.client_1_video.setStyleSheet("QLabel{\n"
"    border:none;\n"
"}")
        self.client_1_video.setText("")
        self.client_1_video.setObjectName("client_1_video")
        self.gridLayout.addWidget(self.client_1_video, 3, 0, 1, 3)
        self.client_1_reject = QtWidgets.QPushButton(self.client_1_frame)
        self.client_1_reject.setObjectName("client_1_reject")
        self.gridLayout.addWidget(self.client_1_reject, 1, 1, 1, 1)
        self.line = QtWidgets.QFrame(self.client_1_frame)
        self.line.setMinimumSize(QtCore.QSize(0, 1))
        self.line.setMaximumSize(QtCore.QSize(16777215, 1))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 2, 0, 1, 3)
        self.gridLayout_5.addWidget(self.client_1_frame, 1, 1, 1, 1)
        self.client_2_frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.client_2_frame.sizePolicy().hasHeightForWidth())
        self.client_2_frame.setSizePolicy(sizePolicy)
        self.client_2_frame.setStyleSheet("QFrame{\n"
"    border:1px solid #ABABAB;\n"
"}")
        self.client_2_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.client_2_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.client_2_frame.setObjectName("client_2_frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.client_2_frame)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.client_2_reject = QtWidgets.QPushButton(self.client_2_frame)
        self.client_2_reject.setObjectName("client_2_reject")
        self.gridLayout_3.addWidget(self.client_2_reject, 1, 1, 1, 1)
        self.client_2_accept = QtWidgets.QPushButton(self.client_2_frame)
        self.client_2_accept.setObjectName("client_2_accept")
        self.gridLayout_3.addWidget(self.client_2_accept, 1, 0, 1, 1)
        self.client_2_stop = QtWidgets.QPushButton(self.client_2_frame)
        self.client_2_stop.setObjectName("client_2_stop")
        self.gridLayout_3.addWidget(self.client_2_stop, 0, 2, 1, 1)
        self.client_2_video = QtWidgets.QLabel(self.client_2_frame)
        self.client_2_video.setStyleSheet("QLabel{\n"
"    border:none;\n"
"}")
        self.client_2_video.setText("")
        self.client_2_video.setObjectName("client_2_video")
        self.gridLayout_3.addWidget(self.client_2_video, 3, 0, 1, 3)
        self.client_2_label = QtWidgets.QLabel(self.client_2_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.client_2_label.sizePolicy().hasHeightForWidth())
        self.client_2_label.setSizePolicy(sizePolicy)
        self.client_2_label.setStyleSheet("QLabel{\n"
"    border:none;\n"
"}")
        self.client_2_label.setObjectName("client_2_label")
        self.gridLayout_3.addWidget(self.client_2_label, 0, 0, 1, 2)
        self.line_2 = QtWidgets.QFrame(self.client_2_frame)
        self.line_2.setMinimumSize(QtCore.QSize(0, 1))
        self.line_2.setMaximumSize(QtCore.QSize(16777215, 1))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_3.addWidget(self.line_2, 2, 0, 1, 3)
        self.gridLayout_5.addWidget(self.client_2_frame, 2, 0, 1, 1)
        self.client_3_frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.client_3_frame.sizePolicy().hasHeightForWidth())
        self.client_3_frame.setSizePolicy(sizePolicy)
        self.client_3_frame.setStyleSheet("QFrame{\n"
"    border:1px solid #ABABAB;\n"
"}")
        self.client_3_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.client_3_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.client_3_frame.setObjectName("client_3_frame")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.client_3_frame)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.client_3_reject = QtWidgets.QPushButton(self.client_3_frame)
        self.client_3_reject.setObjectName("client_3_reject")
        self.gridLayout_4.addWidget(self.client_3_reject, 1, 1, 1, 1)
        self.client_3_accept = QtWidgets.QPushButton(self.client_3_frame)
        self.client_3_accept.setObjectName("client_3_accept")
        self.gridLayout_4.addWidget(self.client_3_accept, 1, 0, 1, 1)
        self.client_3_stop = QtWidgets.QPushButton(self.client_3_frame)
        self.client_3_stop.setObjectName("client_3_stop")
        self.gridLayout_4.addWidget(self.client_3_stop, 0, 2, 1, 1)
        self.client_3_label = QtWidgets.QLabel(self.client_3_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.client_3_label.sizePolicy().hasHeightForWidth())
        self.client_3_label.setSizePolicy(sizePolicy)
        self.client_3_label.setStyleSheet("QLabel{\n"
"    border:none;\n"
"}")
        self.client_3_label.setObjectName("client_3_label")
        self.gridLayout_4.addWidget(self.client_3_label, 0, 0, 1, 2)
        self.client_3_video = QtWidgets.QLabel(self.client_3_frame)
        self.client_3_video.setStyleSheet("QLabel{\n"
"    border:none;\n"
"}")
        self.client_3_video.setText("")
        self.client_3_video.setObjectName("client_3_video")
        self.gridLayout_4.addWidget(self.client_3_video, 3, 0, 1, 3)
        self.line_3 = QtWidgets.QFrame(self.client_3_frame)
        self.line_3.setMinimumSize(QtCore.QSize(0, 1))
        self.line_3.setMaximumSize(QtCore.QSize(16777215, 1))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_4.addWidget(self.line_3, 2, 0, 1, 3)
        self.gridLayout_5.addWidget(self.client_3_frame, 2, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Διαδικτυακές κλήσεις video"))
        self.client_1_accept.setText(_translate("MainWindow", "Απάντηση κλήσης"))
        self.client_1_stop.setText(_translate("MainWindow", "Τερματισμός κλήσης"))
        self.client_1_label.setText(_translate("MainWindow", "Τηλεφωνική κλήση από: ... ..."))
        self.client_1_reject.setText(_translate("MainWindow", "Απόρριψη κλήσης"))
        self.client_2_reject.setText(_translate("MainWindow", "Απόρριψη κλήσης"))
        self.client_2_accept.setText(_translate("MainWindow", "Απάντηση κλήσης"))
        self.client_2_stop.setText(_translate("MainWindow", "Τερματισμός κλήσης"))
        self.client_2_label.setText(_translate("MainWindow", "Τηλεφωνική κλήση από: ... ..."))
        self.client_3_reject.setText(_translate("MainWindow", "Απόρριψη κλήσης"))
        self.client_3_accept.setText(_translate("MainWindow", "Απάντηση κλήσης"))
        self.client_3_stop.setText(_translate("MainWindow", "Τερματισμός κλήσης"))
        self.client_3_label.setText(_translate("MainWindow", "Τηλεφωνική κλήση από: ... ..."))
import icons_rc